package com.mzs.main.model;

import com.mzs.main.model.base.BasePmenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Pmenu extends BasePmenu<Pmenu> {
	public static final Pmenu dao = new Pmenu().dao();
}
