package com.mzs.main.model;

import com.mzs.main.model.base.BaseSysrole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sysrole extends BaseSysrole<Sysrole> {
	public static final Sysrole dao = new Sysrole().dao();
}
