package com.mzs.main.model;

import com.mzs.main.model.base.BaseSysuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sysuser extends BaseSysuser<Sysuser> {
	public static final Sysuser dao = new Sysuser().dao();
	
	public Sysuser findUserByName(String username){
		Sysuser sysuser = dao.findFirst("select * from sysuser f where f.username=? and f.status=1",username);
		return sysuser;
	}
}
