package com.mzs.main.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysrole<M extends BaseSysrole<M>> extends Model<M> implements IBean {

	public M setRoleId(java.lang.Long roleId) {
		set("roleId", roleId);
		return (M)this;
	}

	public java.lang.Long getRoleId() {
		return get("roleId");
	}

	public M setRoleName(java.lang.String roleName) {
		set("roleName", roleName);
		return (M)this;
	}

	public java.lang.String getRoleName() {
		return get("roleName");
	}

	public M setRoleDesc(java.lang.String roleDesc) {
		set("roleDesc", roleDesc);
		return (M)this;
	}

	public java.lang.String getRoleDesc() {
		return get("roleDesc");
	}

}
