package com.mzs.main.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public M setMenuId(java.lang.Long menuId) {
		set("menuId", menuId);
		return (M)this;
	}

	public java.lang.Long getMenuId() {
		return get("menuId");
	}

	public M setMenuName(java.lang.String menuName) {
		set("menuName", menuName);
		return (M)this;
	}

	public java.lang.String getMenuName() {
		return get("menuName");
	}

	public M setClassify(java.lang.String classify) {
		set("classify", classify);
		return (M)this;
	}

	public java.lang.String getClassify() {
		return get("classify");
	}

	public M setMsgservice(java.lang.String msgservice) {
		set("msgservice", msgservice);
		return (M)this;
	}

	public java.lang.String getMsgservice() {
		return get("msgservice");
	}

}
