package com.mzs.main.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePmenu<M extends BasePmenu<M>> extends Model<M> implements IBean {

	public M setPmenuId(java.lang.Long pmenuId) {
		set("pmenuId", pmenuId);
		return (M)this;
	}

	public java.lang.Long getPmenuId() {
		return get("pmenuId");
	}

	public M setPmenuName(java.lang.String pmenuName) {
		set("pmenuName", pmenuName);
		return (M)this;
	}

	public java.lang.String getPmenuName() {
		return get("pmenuName");
	}

}
